# old settings
# highlighter: rouge
# paginate: 1
# permalink: /blog//:title
# end of old settings


# Site settings
title: 'Pablo Reyes'
description: 'Desarrollo de software, tecnología, producto y análisis de datos'
url: 'https://pabloreyes.es'
baseurl: ''
lang: 'es'
timezone: 'Europe/Madrid'
#disqus_shortname: 'pabloreyes-es'

author:
  name: 'Pablo Reyes'
  email: 'info@pabloreyes.es'
  github_username:  pabloreyes
  linkedin_username:  pabloreyesalmagro

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 50
permalink: /:title/
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false


sass:
  style: compact # possible values: nested expanded compact compressed


plugins:
  - jekyll-target-blank
  - jekyll-paginate
  - jekyll-sass-converter
  - jekyll-sitemap

exclude:
  - AGENTS.md
  - Gemfile
  - Gemfile.lock
  - README.md
  - about/.agent/
  - about/AGENTS.md
  - about/projects_information/
  - docs/
  - install.sh
  - node_modules/
  - test/
